version: '3.8'

services:
  backend:
    build: ./proyecto-catedra-api
    container_name: proyecto-catedra-api
    ports:
      - "8000:8000"
    networks:
      - appnet
    volumes:
      - ./proyecto-catedra-api:/var/www/html

  frontend:
    build: ./proyecto-catedra-frontend
    container_name: proyecto-catedra-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet
    volumes:
      - ./proyecto-catedra-frontend:/app

networks:
  appnet:
    driver: bridge
